from __future__ import annotations

from html import escape
from pathlib import Path

from .models import ScanReport


def _badge(sev):
    cls={"CRITICAL":"crit","HIGH":"high","MEDIUM":"med","LOW":"low"}.get(sev,"low")
    return f'<span class="badge {cls}">{escape(sev)}</span>'

def render_html(report: ScanReport) -> str:
    findings="".join(
        f"<tr><td>{_badge(f.severity)}</td><td>{escape(f.column or '—')}</td>"
        f"<td>{escape(f.message)}</td><td>{escape(f.remediation)}</td></tr>" for f in report.findings
    ) or '<tr><td colspan="4">No material findings under configured rules.</td></tr>'
    columns="".join(
        f"<tr><td>{escape(c.name)}</td><td>{escape(c.dtype)}</td><td>{c.null_pct:.2f}%</td>"
        f"<td>{c.unique_pct:.2f}%</td><td>{escape(', '.join(c.pii_types) or '—')}</td></tr>" for c in report.columns
    )
    return f"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>DataGuard AI Report</title><style>
body{{font-family:Inter,system-ui,sans-serif;background:#f5f7fb;color:#172033;margin:0}}
main{{max-width:1180px;margin:36px auto;padding:0 22px}} .hero{{background:#111827;color:white;padding:30px;border-radius:18px}}
.cards{{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0}} .card{{background:white;padding:20px;border-radius:14px;box-shadow:0 2px 12px #0001}}
.score{{font-size:34px;font-weight:800}} table{{width:100%;border-collapse:collapse;background:white;border-radius:14px;overflow:hidden;margin:12px 0 28px}}
th,td{{text-align:left;padding:12px;border-bottom:1px solid #e5e7eb;vertical-align:top}} th{{background:#eef2f7}}
.badge{{padding:4px 8px;border-radius:999px;font-size:12px;font-weight:700}} .crit,.high{{background:#fee2e2;color:#991b1b}}
.med{{background:#fef3c7;color:#92400e}} .low{{background:#dcfce7;color:#166534}} code{{word-break:break-all}}
@media(max-width:800px){{.cards{{grid-template-columns:1fr 1fr}}}}
</style></head><body><main><section class="hero"><h1>DataGuard AI</h1><p>Quality & Governance Report</p><code>{escape(report.source)}</code></section>
<section class="cards"><div class="card"><div>Quality</div><div class="score">{report.quality_score}</div></div>
<div class="card"><div>Governance</div><div class="score">{report.governance_score}</div></div>
<div class="card"><div>Rows</div><div class="score">{report.row_count:,}</div></div>
<div class="card"><div>Findings</div><div class="score">{len(report.findings)}</div></div></section>
<h2>Findings</h2><table><thead><tr><th>Severity</th><th>Column</th><th>Finding</th><th>Suggested action</th></tr></thead><tbody>{findings}</tbody></table>
<h2>Column profile</h2><table><thead><tr><th>Column</th><th>Type</th><th>Null</th><th>Unique</th><th>PII</th></tr></thead><tbody>{columns}</tbody></table>
<p>Generated by DataGuard AI v0.2.0. Scores are engineering heuristics, not compliance certifications.</p></main></body></html>"""

def write_html(report: ScanReport, path: str):
    Path(path).write_text(render_html(report), encoding="utf-8")
